/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_linkcoder100788_java_sdl2_JavaSDL2_ScreenCoordinate */

#ifndef _Included_dev_linkcoder100788_java_sdl2_JavaSDL2_ScreenCoordinate
#define _Included_dev_linkcoder100788_java_sdl2_JavaSDL2_ScreenCoordinate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_ScreenCoordinate
 * Method:    initScreenCoordinate
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024ScreenCoordinate_initScreenCoordinate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_ScreenCoordinate
 * Method:    destroyScreenCoordinate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024ScreenCoordinate_destroyScreenCoordinate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_ScreenCoordinate
 * Method:    setX
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024ScreenCoordinate_setX
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_ScreenCoordinate
 * Method:    setY
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024ScreenCoordinate_setY
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_ScreenCoordinate
 * Method:    getX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024ScreenCoordinate_getX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_ScreenCoordinate
 * Method:    getY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024ScreenCoordinate_getY
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
