/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_linkcoder100788_java_sdl2_JavaSDL2_Sprite */

#ifndef _Included_dev_linkcoder100788_java_sdl2_JavaSDL2_Sprite
#define _Included_dev_linkcoder100788_java_sdl2_JavaSDL2_Sprite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Sprite
 * Method:    initSprite
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Sprite_initSprite
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Sprite
 * Method:    initSpritePos
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Sprite_initSpritePos
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Sprite
 * Method:    destroySprite
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Sprite_destroySprite
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Sprite
 * Method:    setX
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Sprite_setX
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Sprite
 * Method:    setY
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Sprite_setY
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
