/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_linkcoder100788_java_sdl2_JavaSDL2_OpenALPlayer */

#ifndef _Included_dev_linkcoder100788_java_sdl2_JavaSDL2_OpenALPlayer
#define _Included_dev_linkcoder100788_java_sdl2_JavaSDL2_OpenALPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_OpenALPlayer
 * Method:    initOpenALPlayer
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024OpenALPlayer_initOpenALPlayer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_OpenALPlayer
 * Method:    destroyOpenALPlayer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024OpenALPlayer_destroyOpenALPlayer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_OpenALPlayer
 * Method:    setPath
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024OpenALPlayer_setPath
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_OpenALPlayer
 * Method:    playSound
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024OpenALPlayer_playSound
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
