/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_linkcoder100788_java_sdl2_JavaSDL2 */

#ifndef _Included_dev_linkcoder100788_java_sdl2_JavaSDL2
#define _Included_dev_linkcoder100788_java_sdl2_JavaSDL2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2
 * Method:    version
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_version
  (JNIEnv *, jclass);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_init
  (JNIEnv *, jclass);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2
 * Method:    quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_quit
  (JNIEnv *, jclass);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2
 * Method:    getTicks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_getTicks
  (JNIEnv *, jclass);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2
 * Method:    help
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_help
  (JNIEnv *, jclass);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2
 * Method:    _debug
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2__1debug
  (JNIEnv *, jclass);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2
 * Method:    getKeycodeFromName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_getKeycodeFromName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2
 * Method:    playSound
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_playSound
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
