/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_linkcoder100788_java_sdl2_JavaSDL2_Window */

#ifndef _Included_dev_linkcoder100788_java_sdl2_JavaSDL2_Window
#define _Included_dev_linkcoder100788_java_sdl2_JavaSDL2_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Window
 * Method:    initWindow
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Window_initWindow
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Window
 * Method:    destroyWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Window_destroyWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Window
 * Method:    pollEvent
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Window_pollEvent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Window
 * Method:    clear
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Window_clear
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Window
 * Method:    present
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Window_present
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Window
 * Method:    drawSprite
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Window_drawSprite
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Window
 * Method:    drawSpriteScaled
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Window_drawSpriteScaled
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Window
 * Method:    drawSpriteBounded
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Window_drawSpriteBounded
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     dev_linkcoder100788_java_sdl2_JavaSDL2_Window
 * Method:    drawSpriteScaledBounded
 * Signature: (JJIZ)V
 */
JNIEXPORT void JNICALL Java_dev_linkcoder100788_java_1sdl2_JavaSDL2_00024Window_drawSpriteScaledBounded
  (JNIEnv *, jclass, jlong, jlong, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
