#include <string>
#include <fstream>
#include <vector>
#include <clang-c/Index.h>
#include <iostream>
#include <cstring>
#include <algorithm>

#ifndef REFLECTOR_MAJOR
#define REFLECTOR_MAJOR 1
#endif
#ifndef REFLECTOR_MINOR
#define REFLECTOR_MINOR 0
#endif
#ifndef REFLECTOR_PATCH
#define REFLECTOR_PATCH 0
#endif

#define REFLECTOR_VERSION REFLECTOR_MAJOR << "." << REFLECTOR_MINOR << "." << REFLECTOR_PATCH

inline void header_write_header(std::ofstream& header) {
    header << "/* Generated by reflector.cpp \n * At "
    << __TIME__
    << "\n * Reflector version: "
    << REFLECTOR_VERSION
    << "\n */\n";
}

struct Field {
    std::string name;
    std::string type;
};

struct Struct {
    std::string name;
    std::vector<Field> fields;
};

bool has_annotation(CXCursor cursor, const char* target) {
    bool found = false;
    std::pair<bool*, const char*> context(&found, target);
    clang_visitChildren(cursor,
        [](CXCursor c, CXCursor, CXClientData data) {
            auto* ctx = static_cast<std::pair<bool*, const char*>*>(data);
            if (clang_getCursorKind(c) == CXCursor_AnnotateAttr) {
                CXString s = clang_getCursorSpelling(c);
                if (strcmp(clang_getCString(s), ctx->second) == 0) {
                    *ctx->first = true;
                }
                clang_disposeString(s);
            }
            return CXChildVisit_Continue;
        },
        &context
    );
    return found;
}

CXChildVisitResult field_visitor(CXCursor cursor, CXCursor, CXClientData data) {
    if (clang_getCursorKind(cursor) == CXCursor_FieldDecl) {
        if (has_annotation(cursor, "reflected")) {
            auto* current_struct = static_cast<Struct*>(data);

            CXString name = clang_getCursorSpelling(cursor);
            CXString type = clang_getTypeSpelling(clang_getCursorType(cursor));

            current_struct->fields.push_back({
                clang_getCString(name),
                clang_getCString(type)
            });

            clang_disposeString(name);
            clang_disposeString(type);
        }
    }
    return CXChildVisit_Continue;
}

CXChildVisitResult main_visitor(CXCursor cursor, CXCursor, CXClientData data) {
    CXCursorKind kind = clang_getCursorKind(cursor);

    if (kind == CXCursor_StructDecl) {
        if (has_annotation(cursor, "reflected")) {
            auto* structs = static_cast<std::vector<Struct>*>(data);

            CXString type_spelling = clang_getTypeSpelling(clang_getCursorType(cursor));
            std::string name = clang_getCString(type_spelling);
            clang_disposeString(type_spelling);

            if (name.find("struct ") == 0) name = name.substr(7);

            // DEDUPLICATION FIX: Check if we've already parsed this struct
            bool already_exists = std::any_of(structs->begin(), structs->end(),
                [&name](const Struct& existing) { return existing.name == name; });

            if (!already_exists) {
                Struct s;
                s.name = name;
                clang_visitChildren(cursor, field_visitor, &s);
                structs->push_back(s);
            }
        }
    }

    return CXChildVisit_Recurse;
}

void generate_header(const Struct& s, std::ofstream& out) {
    for (auto& f : s.fields) {
        out << "PyObject* " << s.name << "_get_" << f.name << "(PyObject* self, PyObject* closure);\n";
        out << "PyObject* " << s.name << "_set_" << f.name << "(PyObject* self, PyObject* args);\n";
    }

    out << "\n";

    out << "#define " << s.name << "_REFLECTED_METHODS \\\n";
    for (auto& f : s.fields) {
        out << "    { \"get_" << f.name << "\", (PyCFunction)" << s.name
            << "_get_" << f.name << ", METH_NOARGS, \"(This function was generated with compile-time reflection at " << __TIME__ << " On " << __DATE__ << " With Reflector Version " << REFLECTOR_MAJOR << "." << REFLECTOR_MINOR << "." << REFLECTOR_PATCH << "): Get " << f.name << "\" }, \\\n";

        out << "    { \"set_" << f.name << "\", (PyCFunction)" << s.name
            << "_set_" << f.name << ", METH_VARARGS, \"(This function was generated with compile-time reflection at " << __TIME__ << " On " << __DATE__ << " With Reflector Version " << REFLECTOR_MAJOR << "." << REFLECTOR_MINOR << "." << REFLECTOR_PATCH << "): Set " << f.name << "\" }, \\\n";
    }
    out << "\n";
}

void generate_source(const Struct& s, std::ofstream& out) {
    for (auto& f : s.fields) {
        out << "PyObject* " << s.name << "_get_" << f.name << "(PyObject* self, PyObject* closure) {\n";
        out << "    return PyLong_FromLong(((" << s.name << "*)self)->" << f.name << ");\n";
        out << "}\n\n";

        out << "PyObject* " << s.name << "_set_" << f.name << "(PyObject* self, PyObject* args) {\n";
        out << "    int value;\n";
        out << "    if (!PyArg_ParseTuple(args, \"i\", &value)) return NULL;\n";
        out << "    ((" << s.name << "*)self)->" << f.name << " = value;\n";
        out << "    Py_RETURN_NONE;\n";
        out << "}\n\n";
    }
}

int main(int argc, char** argv) {
    if (argc < 3) return 1;

    std::string input = argv[1];
    std::string outDir = argv[2];

    CXIndex index = clang_createIndex(0, 0);
    CXTranslationUnit unit = clang_parseTranslationUnit(
        index, input.c_str(), nullptr, 0, nullptr, 0, CXTranslationUnit_None
    );
    if (!unit) return 1;
    std::vector<Struct> reflected_structs;
    CXCursor cursor = clang_getTranslationUnitCursor(unit);
    clang_visitChildren(cursor, main_visitor, &reflected_structs);
    std::ofstream h(outDir + "/generated_reflect.h");
    std::ofstream c(outDir + "/generated_reflect.c");
    header_write_header(h);
    h << "#pragma once\n";
    h << "#include <Python.h>\n\n";
    c << "#include <Python.h>\n";
    size_t last_slash = input.find_last_of('/');
    std::string header_name = (last_slash == std::string::npos) ? input : input.substr(last_slash + 1);
    c << "#include \"" << header_name << "\"\n";
    c << "#include \"generated_reflect.h\"\n\n";
    for (const auto& s : reflected_structs) {
        if (s.name.find("(unnamed") != std::string::npos) continue;
        generate_header(s, h);
        generate_source(s, c);
    }
    clang_disposeTranslationUnit(unit);
    clang_disposeIndex(index);
    return 0;
}